### ISSUE TITLE
example sketch for 2 sensors

### ISSUE THREAD

**Issue by cweinhofer** [DrGFreeman/SharpDistSensor#14]
Could you include an example sketch for attaching two of these sensors to a board? It would be a big help for newbies like me. I know I have to duplicate and give unique names to some of the stuff in the sketch, but I'm not sure exactly which parts.

Thanks!

**Comment by DrGFreeman** [comment]
Hello @cweinhofer, thank for your interest in this library.

The [SharpDistSensorArray](https://github.com/DrGFreeman/SharpDistSensor/blob/master/examples/SharpDistSensorArray/SharpDistSensorArray.ino) example shows how to use multiple sensors into an array. As written, the example defines two sensors on pins *A1* and *A2*. You should be able to use this example as-is by simply adjusting the pins to match those you are using.

In the main loop, you can access the distances measured by the first and second sensors using `distArray  [0]` and `distArray[1]` respectively.

Hope this helps!

**Comment by cweinhofer** [comment]
Thank you. This was very helpful. I was not familiar with sensor arrays.

I know the problem was due to my ignorance, but maybe you could include two `Serial.print` lines in the array example to make it more obvious for newbies.

**Comment by DrGFreeman** [comment]
> I was not familiar with sensor arrays

In this case it is an array of `SharpDistSensor` objects. FYI you can use arrays of other types of objects of variable types as well. See https://www.arduino.cc/reference/en/language/variables/data-types/array/ for more info on arrays in Arduino.

> maybe you could include two Serial.print lines

I had thought about this however since the example is made to be generic, i.e. can be used for any number of sensors, putting two `Serial.print` statements would break the generic aspect of the example. I could put the print statements in a for loop but I don't think it would help beginners either.

Instead I suggest I could add a comment indicating that the distances from each sensor can be accessed through the indices of the `distArray` variable as in my comment above. Let me know what you think about that.

Regards.
